# Generated by Django 5.2.15 on 2026-06-26 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTB',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20, unique=True)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TasksTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Description', models.TextField()),
                ('Status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDoList.usertb')),
            ],
        ),
    ]
